
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.CURSOS
{

using System;
    using System.Collections.Generic;
    
public partial class ViewUsuarioMatricula
{

    public int ViewUsuarioMatriculaId { get; set; }

    public int CursoOnlineId { get; set; }

    public Nullable<System.DateTime> FechaDescarga { get; set; }

}

}
