
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.CURSOS
{

using System;
    using System.Collections.Generic;
    
public partial class ViewUsuarioMatriculaCursoOnline
{

    public int UsuarioId { get; set; }

    public string NombreUsuario { get; set; }

    public string ApellidoUsuario { get; set; }

    public string EmailUsuario { get; set; }

    public Nullable<int> EmpresaId { get; set; }

    public string NombreCursoOnline { get; set; }

    public decimal PorcentajeAprobacionCursoOnline { get; set; }

    public int CursoOnlineId { get; set; }

    public int MatriculaCursoOnlineId { get; set; }

    public System.DateTime FechaMatricula { get; set; }

    public Nullable<System.DateTime> FechaCompletado { get; set; }

    public Nullable<System.DateTime> FechaAprobado { get; set; }

    public Nullable<decimal> PorcentajeObtenido { get; set; }

}

}
