
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.PARAMETROS
{

using System;
    using System.Collections.Generic;
    using PROMPERU.AULAVIRTUAL.BE.CURSOS;
    using PROMPERU.AULAVIRTUAL.BE.USUARIO;

    public partial class ParametroScorm
{

    public int ParametroScormId { get; set; }

    public int UnidadCursoOnlineId { get; set; }

    public int UsuarioId { get; set; }

    public string Parametro { get; set; }

    public string Valor { get; set; }

    public Nullable<int> MatriculaCursoOnlineId { get; set; }



    public virtual MatriculaCursoOnline MatriculaCursoOnline { get; set; }

    public virtual UnidadCursoOnline UnidadCursoOnline { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
