
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.USUARIO
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empresa()
    {

        this.UsuarioMultiEmpresa = new HashSet<UsuarioMultiEmpresa>();

        this.Usuario = new HashSet<Usuario>();

    }


    public int EmpresaId { get; set; }

    public string RUC { get; set; }

    public string RazonSocial { get; set; }

    public bool AutoMatriculaHabilitada { get; set; }

    public string Email { get; set; }

    public string CIIU { get; set; }

    public string Productos { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UsuarioMultiEmpresa> UsuarioMultiEmpresa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Usuario> Usuario { get; set; }

}

}
