
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.USUARIO
{

using System;
    using System.Collections.Generic;
    using PROMPERU.AULAVIRTUAL.BE.CURSOS;
public partial class UsuarioGrupo
{

    public int UsuarioGrupoId { get; set; }

    public int GrupoId { get; set; }

    public int UsuarioId { get; set; }

    public string Estado { get; set; }

    public string Nombre { get; set; }



    public virtual Grupo Grupo { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
