
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.BE.USUARIO
{
using System;
    using System.Collections.Generic;
    
public partial class UsuarioMultiEmpresa
{

    public int UsuarioMultiEmpresaId { get; set; }

    public int UsuarioId { get; set; }

    public int EmpresaId { get; set; }



    public virtual Empresa Empresa { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
