
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class CambioContrasena
//{

//    public int CambioContrasenaId { get; set; }

//    public System.DateTime Fecha { get; set; }

//    public string Token { get; set; }

//    public int UsuarioId { get; set; }

//    public Nullable<System.DateTime> FechaCambio { get; set; }



//    public virtual Usuario Usuario { get; set; }

//}

//}
