
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class CMS_MenuItem
//{

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public CMS_MenuItem()
//    {

//        this.CMS_MenuItem1 = new HashSet<CMS_MenuItem>();

//    }


//    public int Id { get; set; }

//    public int MenuId { get; set; }

//    public Nullable<int> PageId { get; set; }

//    public Nullable<int> ParentMenuItemId { get; set; }

//    public string CustomUrl { get; set; }

//    public string Titulo { get; set; }

//    public int Orden { get; set; }

//    public bool EsPublicado { get; set; }

//    public Nullable<System.DateTime> FechaEdicion { get; set; }

//    public Nullable<int> UsuarioEdicionId { get; set; }



//    public virtual CMS_Menu CMS_Menu { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<CMS_MenuItem> CMS_MenuItem1 { get; set; }

//    public virtual CMS_MenuItem CMS_MenuItem2 { get; set; }

//    public virtual CMS_Page CMS_Page { get; set; }

//}

//}
