
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class CMS_Page
//{

//    //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public CMS_Page()
//    {

//        this.CMS_MenuItem = new HashSet<CMS_MenuItem>();

//    }


//    public int Id { get; set; }

//    public string Nombre { get; set; }

//    public string Url { get; set; }

//    public string RutaPagina { get; set; }

//    public string RutaLayout { get; set; }

//    public bool EsPublicado { get; set; }

//    public Nullable<System.DateTime> FechaEdicion { get; set; }

//    public Nullable<int> UsuarioEdicionId { get; set; }



//    //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<CMS_MenuItem> CMS_MenuItem { get; set; }

//}

//}
