
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class CMS_Label
//{

//    public int CMS_LabelId { get; set; }

//    public string Codigo { get; set; }

//    public string Texto { get; set; }

//    public bool EsRaw { get; set; }

//    public string TipoComponente { get; set; }

//    public Nullable<System.DateTime> FechaModificacion { get; set; }

//}

//}
