
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class CursoGrupo
//{

//    public int CursoGrupoId { get; set; }

//    public Nullable<int> GrupoId { get; set; }

//    public Nullable<int> CursoOnlineMaestroId { get; set; }

//    public string Estado { get; set; }

//    public string Nombre { get; set; }



//    public virtual CursoOnlineMaestro CursoOnlineMaestro { get; set; }

//    public virtual Grupo Grupo { get; set; }

//}

//}
