
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class Distrito
//{

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public Distrito()
//    {

//        this.Usuario = new HashSet<Usuario>();

//    }


//    public int DistritoId { get; set; }

//    public int ProvinciaId { get; set; }

//    public int DepartamentoId { get; set; }

//    public string Nombre { get; set; }

//    public int EstadoId { get; set; }

//    public string Ubigeo { get; set; }



//    public virtual Departamento Departamento { get; set; }

//    public virtual Provincia Provincia { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<Usuario> Usuario { get; set; }

//}

//}
