
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class Grupo
//{

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public Grupo()
//    {

//        this.CursoGrupo = new HashSet<CursoGrupo>();

//        this.UsuarioGrupo = new HashSet<UsuarioGrupo>();

//    }


//    public int GrupoId { get; set; }

//    public string Descripcion { get; set; }

//    public string Estado { get; set; }

//    public Nullable<System.DateTime> FechaCreacion { get; set; }

//    public Nullable<int> Aforo { get; set; }

//    public string TipoRegistro { get; set; }



//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<CursoGrupo> CursoGrupo { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<UsuarioGrupo> UsuarioGrupo { get; set; }

//}

//}
