
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class LogAccesosUsuario
//{

//    public int LogAccesoUsuarioId { get; set; }

//    public System.DateTime FechaAcceso { get; set; }

//    public string DatosNavegador { get; set; }

//    public string UserAgent { get; set; }

//    public string TipoAcceso { get; set; }

//    public int UsuarioId { get; set; }

//    public string IPAcceso { get; set; }



//    public virtual Usuario Usuario { get; set; }

//}

//}
