
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{
//    using PROMPERU.AULAVIRTUAL.BE.CURSOS;
//    using System;
//    using System.Collections.Generic;
    
//public partial class LogUnidad
//{

//    public int LogUnidadId { get; set; }

//    public string Estado { get; set; }

//    public System.DateTime FechaRegistro { get; set; }

//    public int UnidadCursoOnlineId { get; set; }

//    public int MatriculaCursoOnlineId { get; set; }

//    public int UsuarioId { get; set; }



//    public virtual MatriculaCursoOnline MatriculaCursoOnline { get; set; }

//    public virtual UnidadCursoOnline UnidadCursoOnline { get; set; }

//    public virtual Usuario Usuario { get; set; }

//}

//}
