
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class PreguntaCursoOnline
//{

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public PreguntaCursoOnline()
//    {

//        this.PreguntaEvaluacionCursoOnline = new HashSet<PreguntaEvaluacionCursoOnline>();

//        this.RespuestaCursoOnline = new HashSet<RespuestaCursoOnline>();

//    }


//    public int PreguntaCursoOnlineId { get; set; }

//    public Nullable<int> CursoOnlineId { get; set; }

//    public string Tipo { get; set; }

//    public int NumRespuestas { get; set; }

//    public string Texto { get; set; }

//    public int Puntaje { get; set; }

//    public string Estado { get; set; }

//    public int UnidadOnlineId { get; set; }



//    public virtual UnidadCursoOnline UnidadCursoOnline { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<PreguntaEvaluacionCursoOnline> PreguntaEvaluacionCursoOnline { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<RespuestaCursoOnline> RespuestaCursoOnline { get; set; }

//    public virtual CursoOnline CursoOnline { get; set; }

//}

//}
