
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class RespuestaCursoOnline
//{

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
//    public RespuestaCursoOnline()
//    {

//        this.RespuestaEvaluacionCursoOnline = new HashSet<RespuestaEvaluacionCursoOnline>();

//        this.RespuestaSeleccionadaEvaluacionCursoOnline = new HashSet<RespuestaSeleccionadaEvaluacionCursoOnline>();

//    }


//    public int RespuestaCursoOnlineId { get; set; }

//    public int PreguntaCursoOnlineId { get; set; }

//    public string Texto { get; set; }

//    public bool EsSolucion { get; set; }

//    public Nullable<int> OrdenSolucion { get; set; }



//    public virtual PreguntaCursoOnline PreguntaCursoOnline { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<RespuestaEvaluacionCursoOnline> RespuestaEvaluacionCursoOnline { get; set; }

//    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

//    public virtual ICollection<RespuestaSeleccionadaEvaluacionCursoOnline> RespuestaSeleccionadaEvaluacionCursoOnline { get; set; }

//}

//}
