
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class RespuestaEvaluacionCursoOnline
//{

//    public int RespuestaEvaluacionCursoOnlineId { get; set; }

//    public int PreguntaEvaluacionCursoOnlineId { get; set; }

//    public int RespuestaCursoOnlineId { get; set; }

//    public int OrdenMostrado { get; set; }



//    public virtual PreguntaEvaluacionCursoOnline PreguntaEvaluacionCursoOnline { get; set; }

//    public virtual RespuestaCursoOnline RespuestaCursoOnline { get; set; }

//}

//}
