
////------------------------------------------------------------------------------
//// <auto-generated>
////     Este código se generó a partir de una plantilla.
////
////     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
////     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
//// </auto-generated>
////------------------------------------------------------------------------------


//namespace PROMPERU.AULAVIRTUAL.WEB.Models
//{

//using System;
//    using System.Collections.Generic;
    
//public partial class ViewReporteHistoricoAlumno
//{

//    public Nullable<int> Ususario_UsuarioId { get; set; }

//    public string Usuario_Codigo { get; set; }

//    public string Usuario_Cargo { get; set; }

//    public string Usuario_Grupo { get; set; }

//    public string Usuario_NombreCompleto { get; set; }

//    public string Usuario_Email { get; set; }

//    public Nullable<int> Usuario_EmpresaId { get; set; }

//    public string Usuario_Sexo { get; set; }

//    public string Usuario_Nacionalidad { get; set; }

//    public string Usuario_Ubigeo { get; set; }

//    public string Usuario_Distrito { get; set; }

//    public string Usuario_Provincia { get; set; }

//    public string Usuario_Departamento { get; set; }

//    public Nullable<System.DateTime> Usuario_UltimoAcceso { get; set; }

//    public string Usuario_Dni { get; set; }

//    public string Usuario_OtroDoc { get; set; }

//    public string Empresa_RazonSocial { get; set; }

//    public string Empresa_RUC { get; set; }

//    public string Curso_Nombre { get; set; }

//    public Nullable<int> Curso_CursoOnlineId { get; set; }

//    public string Usuario_Estado { get; set; }

//    public int Matricula_MatriculaCursoOnlineId { get; set; }

//    public string Matricula_Estado { get; set; }

//    public System.DateTime Matricula_FechaMatricula { get; set; }

//    public Nullable<System.DateTime> Matricula_FechaCompletado { get; set; }

//    public Nullable<System.DateTime> Matricula_FechaAprobado { get; set; }

//    public decimal Matricula_PorcentajeAvance { get; set; }

//    public Nullable<decimal> Matricula_PorcentajeObtenido { get; set; }

//    public Nullable<decimal> Matricula_Nota { get; set; }

//}

//}
