
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.WEB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ViewReporteHistoricoAlumnoLst
{

    public string Usuario_Dni { get; set; }

    public string Usuario_OtroDoc { get; set; }

    public string Ruc { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public string Rol { get; set; }

    public string Email { get; set; }

    public string Estado { get; set; }

    public string Departamento { get; set; }

    public string Provincia { get; set; }

    public string Distrito { get; set; }

    public string Nacionalidad { get; set; }

    public string TieneConstancia { get; set; }

}

}
