
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROMPERU.AULAVIRTUAL.WEB.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ViewCertificadoAlumno
{

    public string Nombre { get; set; }

    public int UsuarioId { get; set; }

    public int CursoOnlineMaestroId { get; set; }

    public Nullable<decimal> PorcentajeObtenido { get; set; }

    public Nullable<decimal> PorcentajeAvance { get; set; }

    public Nullable<int> CantidadCursos { get; set; }

}

}
